### ISSUE TITLE
Fix null error when typing /f info after updating to v3.5

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#649]

**Comment by dmccoystephenson** [comment]
**Here is a picture of what happens**
![image](https://user-images.githubusercontent.com/21204351/92317135-b94ce000-efba-11ea-9958-75e68eac244c.png)

**and the error message:**
`[05-09-2020 20:59:19] DanTheTechMan issued server command: /f info
[05-09-2020 20:59:19] null
[05-09-2020 20:59:19] org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin MedievalFactions v3.5
[05-09-2020 20:59:19] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:747) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1702) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1545) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[05-09-2020 20:59:19] Caused by: java.lang.NullPointerException
[05-09-2020 20:59:19] at factionsystem.Objects.Faction.isLiege(Faction.java:577) ~[?:?]
[05-09-2020 20:59:19] at factionsystem.Subsystems.UtilitySubsystem.sendFactionInfo(UtilitySubsystem.java:569) ~[?:?]
[05-09-2020 20:59:19] at factionsystem.Commands.InfoCommand.showInfo(InfoCommand.java:25) ~[?:?]
[05-09-2020 20:59:19] at factionsystem.Subsystems.CommandSubsystem.interpretCommand(CommandSubsystem.java:107) ~[?:?]
[05-09-2020 20:59:19] at factionsystem.Main.onCommand(Main.java:101) ~[?:?]
[05-09-2020 20:59:19] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-758abbe-ca19c2f]
[05-09-2020 20:59:19] ... 18 more`

**Comment by dmccoystephenson** [comment]
It looks like claimed chunks don't get loaded for some reason as well.

**Comment by dmccoystephenson** [comment]
I opened a draft PR for this bug. If you want to help try to fix it, please use that branch.
